CREATE TABLE contact_roles (
    id VARCHAR(36) PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    contact_role CHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    CONSTRAINT fk_account_id FOREIGN KEY (account_id)
        REFERENCES contacts(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
